// src/lib/jobs/mock-data.ts

import type { JobListing } from '@/types/job-search';

export const MOCK_JOBS: JobListing[] = [
  {
    id: 'job-1',
    title: 'Senior Full Stack Engineer',
    company: 'Nexus Labs',
    location: 'Remote (US)',
    salary: '$150K-$200K',
    description:
      'Lead product engineering for a high-growth fintech platform. Own end-to-end feature delivery, mentor junior engineers, and drive architecture decisions across React, Node, and PostgreSQL.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-28',
    source: 'linkedin',
  },
  {
    id: 'job-2',
    title: 'Staff Frontend Developer',
    company: 'Orbit Systems',
    location: 'Berlin, Germany',
    salary: '€110K-€140K',
    description:
      'Design and build performant, accessible UI components for a developer tooling suite. Deep expertise in TypeScript, React, and design systems is required.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-25',
    source: 'indeed',
  },
  {
    id: 'job-3',
    title: 'DevOps Engineer II',
    company: 'CloudPath',
    location: 'London, UK (Hybrid)',
    salary: '£75K-£95K',
    description:
      'Maintain CI/CD pipelines, Kubernetes clusters, and Terraform infrastructure. Collaborate with platform teams to improve reliability, observability, and deployment velocity.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-29',
    source: 'linkedin',
  },
  {
    id: 'job-4',
    title: 'Product Engineer — AI Infrastructure',
    company: 'Cortex AI',
    location: 'San Francisco, CA',
    salary: '$180K-$240K',
    description:
      'Build infrastructure and APIs that power large-language-model features. Strong Python, AWS, and distributed systems experience preferred.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-20',
    source: 'glassdoor',
  },
  {
    id: 'job-5',
    title: 'Senior Backend Engineer (Go)',
    company: 'StreamForge',
    location: 'Remote (EU)',
    salary: '€95K-€130K',
    description:
      'Develop high-throughput streaming services in Go. Focus on API design, performance tuning, and event-driven architecture with Kafka.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-30',
    source: 'linkedin',
  },
  {
    id: 'job-6',
    title: 'Engineering Manager — Platform',
    company: 'Atlas Ventures',
    location: 'New York, NY (Hybrid)',
    salary: '$190K-$260K',
    description:
      'Lead a platform team of 8-10 engineers. Balance people leadership, technical strategy, and cross-functional delivery for internal developer experience.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-22',
    source: 'indeed',
  },
  {
    id: 'job-7',
    title: 'Mobile Engineer (React Native)',
    company: 'PocketHealth',
    location: 'Remote (Global)',
    salary: '$120K-$160K',
    description:
      'Ship cross-platform mobile features for a health-tech consumer app. Experience with React Native, performance profiling, and native module integration is a plus.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-07-01',
    source: 'linkedin',
  },
  {
    id: 'job-8',
    title: 'Security Software Engineer',
    company: 'ShieldOps',
    location: 'Austin, TX',
    salary: '$140K-$185K',
    description:
      'Design secure-by-default services and drive vulnerability remediation. Background in application security, cloud IAM, and secure SDLC practices.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-27',
    source: 'glassdoor',
  },
  {
    id: 'job-9',
    title: 'Data Engineer',
    company: 'Insightly',
    location: 'Toronto, ON (Hybrid)',
    salary: 'C$110K-C$150K',
    description:
      'Build scalable data pipelines and analytics products. Strong SQL, Python, and cloud data warehouse experience required.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-24',
    source: 'indeed',
  },
  {
    id: 'job-10',
    title: 'UX Engineer',
    company: 'Pixelworks',
    location: 'Remote (North America)',
    salary: '$130K-$170K',
    description:
      'Bridge design and engineering by implementing polished UI in React and Tailwind CSS. Strong collaboration with product designers and design-system ownership.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-26',
    source: 'linkedin',
  },
  {
    id: 'job-11',
    title: 'Site Reliability Engineer',
    company: 'UptimeFirst',
    location: 'Singapore',
    salary: 'S$120K-S$160K',
    description:
      'Own reliability engineering for a global SaaS product. On-call rotation, incident management, and infrastructure automation with Terraform and Ansible.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-21',
    source: 'linkedin',
  },
  {
    id: 'job-12',
    title: 'Technical Lead — E-commerce',
    company: 'VoltCommerce',
    location: 'Amsterdam, Netherlands',
    salary: '€100K-€135K',
    description:
      'Lead a cross-functional squad building checkout and payment experiences. Hands-on coding in TypeScript/Node plus architecture and mentoring responsibilities.',
    matchScore: 0,
    matchedSkills: [],
    missingSkills: [],
    postedDate: '2026-06-23',
    source: 'indeed',
  },
];
